version: 2
project_name: "k8see-importer"
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    id: lin

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ["binary"]

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "latest"

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=GOOS=linux"
      - "--build-arg=GOARCH=amd64"
    extra_files:
    - resources

  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/sgaunet/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=GOOS=linux"
      - "--build-arg=GOARCH=arm64"
    extra_files:
    - resources

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/sgaunet/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/sgaunet/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-amd64
      - ghcr.io/sgaunet/{{ .ProjectName }}:latest-arm64v8


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'