# https://taskfile.dev
version: '3'

vars:
  BINFILE: k8see-importer
  IMG: ghcr.io/sgaunet/k8see-importer:latest

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 go build .

  image:
    desc: "Build the image"
    deps: 
    - build
    cmds:
      - docker build . -t {{.IMG}}

  push:
    desc: "Build and push the image (latest)"
    deps: 
    - image
    cmds:
      - docker push {{.IMG}}

  snapshot:
    desc: "Create a snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean