# https://taskfile.dev
version: '3'

vars:
  BINFILE: k8see-importer
  IMG: ghcr.io/sgaunet/k8see-importer:latest

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  linter:
    desc: "Run linter"
    cmds:
      - go generate ./...
      - golangci-lint run

  build:
    desc: "Build the binary"
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 go build .

  image:
    desc: "Build/Push the image"
    deps: 
    - snapshot
    cmds:
      - docker tag ghcr.io/sgaunet/k8see-importer:latest-amd64 {{.IMG}}
      - docker push {{.IMG}}

  snapshot:
    desc: "Create a snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean